[header,
    [searchSortSection, 
        [searchBarContainer, 
            searchBar],
        [sortButtonSection, 
            sortButton,
            selectProject
        ]
    ],
    [buttonSection,
        addTodo,
        deleteCompleted,
        createProject,
        manageProjects,
    ]
]